<font color='violet'><h2>Pandas:</h2></font>
Panel Data and Analysis

* Pandas is a python library used for working with data sets.
* It has functioning for analyzing, cleaning, exploring and manipulating data.
* It was created in 2008 by Wes Mckinney.

> <font color='yellow'><h4>What kind of data is best suited for PANDAS?</h4></font>
- Rows & columns
- Excel, .xlsxs, .csv[comma separated values],.workbook

<font color='red'><h3>Data Frames:</h3></font> Rows and Columns [2-D array]
<font color='red'><h3>Data Series:</h3></font> [1-D array]

In [4]:
import pandas as pd
#Create a simple pandas series from a list data structure(Ds).
a=[10,20,30,'Late','Punishment']
my_col=pd.Series(a)
print(my_col) #This wil print data series

0            10
1            20
2            30
3          Late
4    Punishment
dtype: object


<font color='green'><h2>Labels:</h2></font> It is the index.If nothing is passed then column elements will have normal indexing which starts from 0. It can be used to access any element of the series

In [1]:
import pandas as pd
#Create a simple pandas series from a list data structure(Ds).
a=[10,20,30,'Late','Punishment']
my_col=pd.Series(a)
print(my_col) 
print(my_col[2])

0            10
1            20
2            30
3          Late
4    Punishment
dtype: object
30


In [7]:
import pandas as pd
b=[15,20,35]
s=pd.Series(b, index=['x','y','z'])
print(s)

x    15
y    20
z    35
dtype: int64


In [8]:
#Creating series through an array
import pandas as pd
import numpy as np
arr=np.array([1,2,3,4,5,6])
a=pd.Series(arr)
print(a)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [10]:
#Creating a series through a dictionary
import pandas as pd
dict={'a':10,'b':20,'c':30}
ds1=pd.Series(dict)
print(ds1)

a    10
b    20
c    30
dtype: int64


In [11]:
import pandas as pd
dict={'a':10,'b':20,'c':30}
ds1=pd.Series(dict, index=['x','y','z'])
print(ds1) #NaN because a,b,c already  have fixed value

x   NaN
y   NaN
z   NaN
dtype: float64


In [13]:
#Creating a Series of a particular scalar value with your own index
import pandas as pd
import numpy as np
x=pd.Series(20,index=[1,2,3,4,5])
y=np.zeros((2,4))
z=np.ones((3,5))
print(x)
print(y)
print(z)

1    20
2    20
3    20
4    20
5    20
dtype: int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<font color='blue'><h1>Data Frames:</h1></font> Data-sets in Pandas are usually multi-dimensionals tables, known as "DataFrames."
* Data Frame is a whole table, whereas Series is like a column.
* Data Frame is heterogeneous i.e, collection of different type of value.

In [15]:
#1.Creating a DataFrame from 3-list.
import pandas as pd
data={"Names":["Muthu","Swami","Ayyer"],"Roll No":[101,102,103],"Marks":[4,7,6]}
df=pd.DataFrame(data)
print(df)

   Names  Roll No  Marks
0  Muthu      101      4
1  Swami      102      7
2  Ayyer      103      6


In [17]:
import pandas as pd
data={"Names":["Muthu","Swami","Ayyer"],"Roll No":[101,102,103],"Marks":[4,7,6]}
print(pd.DataFrame(data, index=['a','b','c']))

   Names  Roll No  Marks
a  Muthu      101      4
b  Swami      102      7
c  Ayyer      103      6


In [27]:
#To check the location of data
import pandas as pd
data={"Names":["Muthu","Swami","Ayyer"],"Roll No":[101,102,103],"Marks":[4,7,6]}
df=pd.DataFrame(data, index=['a','b','c'])
print(df.loc['a','Names']) #Accesing values of keys by indexing

Muthu


In [28]:
#Creating DataFrames using numpy
npar=np.array([['abc','xyz','mno'],[101,102,103],[50,80,85]])
df1=pd.DataFrame(npar,columns=['ID1','ID2','ID3'], index=['Names','Roll No.','Marks'])
print(df1)

          ID1  ID2  ID3
Names     abc  xyz  mno
Roll No.  101  102  103
Marks      50   80   85


In [5]:
s1=pd.Series(['Shreya','Dev','nisha','Mansi'],index=[1,2,3,4])
s2=pd.Series(['124','245','252','167'],index=[1,2,3,4])
s3=pd.Series([23,45,67,88],index=[1,2,3,4])
x={'Names':s1,'Roll NO.':s2,'Marks':s3}
y=pd.DataFrame(x)
print(y)

    Names Roll NO.  Marks
1  Shreya      124     23
2     Dev      245     45
3   nisha      252     67
4   Mansi      167     88


In [6]:
#Inserting a new column in existing DF.
x={'Names':s1,'Roll NO.':s2,'Marks':s3}
y=pd.DataFrame(x)
y['Address']=['Noida','Delhi','NewYork','usa']
print(y)

y['pra_status']=y['Marks']>80
print(y)

    Names Roll NO.  Marks  Address
1  Shreya      124     23    Noida
2     Dev      245     45    Delhi
3   nisha      252     67  NewYork
4   Mansi      167     88      usa
    Names Roll NO.  Marks  Address  pra_status
1  Shreya      124     23    Noida       False
2     Dev      245     45    Delhi       False
3   nisha      252     67  NewYork       False
4   Mansi      167     88      usa        True


In [7]:
#Inserting a new column at a desired location in data frame.
y.insert(1,'Section',['A','B','c','D'])
#insert(location,col_name,values)
print(y)

    Names Section Roll NO.  Marks  Address  pra_status
1  Shreya       A      124     23    Noida       False
2     Dev       B      245     45    Delhi       False
3   nisha       c      252     67  NewYork       False
4   Mansi       D      167     88      usa        True


In [8]:
#Deleting any column from DF
del y['pra_status']
print(y)

    Names Section Roll NO.  Marks  Address
1  Shreya       A      124     23    Noida
2     Dev       B      245     45    Delhi
3   nisha       c      252     67  NewYork
4   Mansi       D      167     88      usa


In [9]:
a=y.pop('Section')
print(a)

1    A
2    B
3    c
4    D
Name: Section, dtype: object


In [11]:
#Make a dataframe by using arange()
import pandas as pd
import numpy as np
x=np.arange(10,40)
print(x)
y1=pd.DataFrame(x)
print(y1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]
     0
0   10
1   11
2   12
3   13
4   14
5   15
6   16
7   17
8   18
9   19
10  20
11  21
12  22
13  23
14  24
15  25
16  26
17  27
18  28
19  29
20  30
21  31
22  32
23  33
24  34
25  35
26  36
27  37
28  38
29  39


In [13]:
#Writing to a file
print(y)
y.to_csv(r"C:\Users\kushw\Downloads\Shreya.csv")

    Names Roll NO.  Marks  Address
1  Shreya      124     23    Noida
2     Dev      245     45    Delhi
3   nisha      252     67  NewYork
4   Mansi      167     88      usa


In [15]:
y.to_excel(r"C:\Users\kushw\Downloads\Shreya1.xlsx")

In [16]:
#Reading a csv file
y=pd.read_csv(r"C:\Users\kushw\Downloads\Shreya.csv")
print(y)

   Unnamed: 0   Names  Roll NO.  Marks  Address
0           1  Shreya       124     23    Noida
1           2     Dev       245     45    Delhi
2           3   nisha       252     67  NewYork
3           4   Mansi       167     88      usa


In [19]:
a=pd.read_csv(r"C:\Users\kushw\Downloads\employee.csv")
print(a)

       Unnamed: 0 Series_reference   Period  Data_value Suppressed STATUS  \
0               0      MFGQ.SFA1CA  1992.12    2493.370        NaN      F   
1               1      MFGQ.SFA1CA  1993.03    3209.200        NaN      F   
2               2      MFGQ.SFA1CA  1993.06    2780.170        NaN      F   
3               3      MFGQ.SFA1CA  1993.09    1933.010        NaN      F   
4               4      MFGQ.SFA1CA  1993.12    2692.920        NaN      F   
...           ...              ...      ...         ...        ...    ...   
30055       30055      MFGQ.SFZ5KA  2024.03   10399.776        NaN      R   
30056       30056      MFGQ.SFZ5KA  2024.06    8981.859        NaN      R   
30057       30057      MFGQ.SFZ5KA  2024.09    9426.188        NaN      R   
30058       30058      MFGQ.SFZ5KA  2024.12   10595.690        NaN      R   
30059       30059      MFGQ.SFZ5KA  2025.03   10826.352        NaN      F   

         UNITS  Magnitude                                Subject  \
0      

In [20]:
print(a.Magnitude.count())

30060


In [22]:
print(a.Data_value.max())
print(a.Data_value.min())

35749.295
-26.0


In [31]:
#Read the csv file
#Calculate the maximum and minimum marks in three subjects.(individually)
#Apply aggregate function on the different groups(columns) in the given file. Perform inner join, outer join, left join and right join
#Change the name of column official  email id to email id.
#provide the name of the students whose score more than 80% in mathematics
#provide the name of the students whose score less than 75% in mathematics
#Add a new column sgpa=total marks /10
#Add a new column grade acc to total marks.
import pandas as pd
x=pd.read_csv(r"C:\Users\kushw\Downloads\C001 Details.csv")
print(x)

    ID        Start time   Completion time                  Email  \
0    1  6-18-25 14:25:10  6-18-25 14:26:56  0241cys090@niet.co.in   
1    2  6-18-25 14:24:54  6-18-25 14:27:52  0241cse367@niet.co.in   
2    3  6-18-25 14:24:58  6-18-25 14:28:06  0241cse304@niet.co.in   
3    4  6-18-25 14:24:49  6-18-25 14:28:11  0241cse142@niet.co.in   
4    5  6-18-25 14:25:09  6-18-25 14:28:17  0241cse268@niet.co.in   
..  ..               ...               ...                    ...   
87  88  6-18-25 14:26:55  6-18-25 14:33:59  0241cse263@niet.co.in   
88  89  6-18-25 14:31:38  6-18-25 14:34:01  0241cse104@niet.co.in   
89  90  6-18-25 14:26:00  6-18-25 14:34:04  0241cse024@niet.co.in   
90  91  6-18-25 14:32:28  6-18-25 14:34:05  0241cse009@niet.co.in   
91  92  6-18-25 14:26:28  6-18-25 14:34:16  0241cse074@niet.co.in   

                    Name  Last modified time       NAME OF STUDENT  \
0   awanish kumar maurya                 NaN  AWANISH KUMAR MAURYA   
1          Harshit Saini       

In [32]:
mx=x[['MARKS IN ENGLISH','MARKS IN MATHS-1','MARKS IN BEEE/PHYSICS','MARKS IN DESIGN THINKING-1','TOTAL MARKS']].max()
print(mx)

MARKS IN ENGLISH               99
MARKS IN MATHS-1               96
MARKS IN BEEE/PHYSICS          98
MARKS IN DESIGN THINKING-1     99
TOTAL MARKS                   753
dtype: object


In [33]:
mn=x[['MARKS IN ENGLISH','MARKS IN MATHS-1','MARKS IN BEEE/PHYSICS','MARKS IN DESIGN THINKING-1','TOTAL MARKS']].min()
print(mn)

MARKS IN ENGLISH                1
MARKS IN MATHS-1                1
MARKS IN BEEE/PHYSICS           1
MARKS IN DESIGN THINKING-1      1
TOTAL MARKS                   203
dtype: object
