<font color='blue'><h1>Libraries in Python:</h1></font>

* NumPy
* Pandas
* MatPlotLib
* Seaborn
* Plotly
* SciPy

<font color='violet'><h2>NumPy:</h2></font>Numeric Python

* Package for scientific computing in Python.
* NumPy is Library that provides *n-dimensional array objects*
* Fast operations on Arrays including logical, shape manipulation, sorting, selectinng, discrete mathematics, Fourier Transforms, Basic Linear Algebra, Stastical operations, Random Simulation and many more.


In [2]:
#1. Defining 1-D array
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a)) #1-D array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#2. To enter element of different type in Array
import numpy as np
b=np.array([3,0.5,7.8,'shreya','kushwaha',8.9,0])
print(b)`
print(type(b))
print(a.dtype)
print(b.dtype)

['3' '0.5' '7.8' 'shreya' 'kushwaha' '8.9' '0']
<class 'numpy.ndarray'>
int32
<U32


<font color='blue'><h1>Reshaping:</h1></font>

* As long as the elements required for reshaping are equal in both shapes.
* E.g:- We can reshape an 8 elements 1-D array into 4 elements in 2 rows 2-D array but we can't reshape it into a 3 elements 3 rows 2-D array.

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<font color='blue'><h1>Resizing: </h1></font>

* The resize() function is used to create a new array with the specified shape.
* If the new array is larger than the original array, then the new array is filled with repeated copies of a.

In [12]:
import numpy as np 
a=np.array([1,2,3,4])
np.resize(a,(3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

<font color='blue'><h1>Difference between Resize and Reshape methods in NumPy:</h1></font>

- Reshape does not change the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.


In [14]:
import numpy as np
cs=np.array([1,2,3,4,5,6])
print("Original array:")
print(cs)
print("Changed array:")
print(cs.reshape(2,3))
print("Changed array:")
print(cs.resize(2,3))
print("Original array:")
print(cs)

Original array:
[1 2 3 4 5 6]
Changed array:
[[1 2 3]
 [4 5 6]]
Changed array:
None
[[1 2 3]
 [4 5 6]]


In [22]:
#Creating 2-D array
import numpy as np
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(type(arr))
print(ar.ndim)
print(ar[2][1])
print(ar[0][2])
r1=ar[:2,:2]
print(r1)

#Reversing array
r2=ar[::-1,::-1]
print(r2)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
2
8
3
[[1 2]
 [4 5]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


<font color='blue'><h1>Attributes in numpy:</h1></font>

* <font color='green'>ndim:</font> Provides dimensions in array.
* <font color='green'>size:</font> Number of elements in array.
* <font color='green'>nbytes:</font> No. of bytes occupied by an array.
* <font color='green'>itemsize:</font> bytes occupied by each elements.

In [26]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
6
9
(6,)
(3, 3)


<font color='green'><h2>Usual Metrices:</h2></font>


In [40]:
import numpy as np
a=np.zeros((2,4),dtype ='int16')
b=np.ones((3,4))
print(a)
print(b)
x=np.full((3,4),10)
print(x)
y=np.full((3,3),np.nan)
print(y)
m=np.diag([10,20,30,40,50]) #Diagonal Matrix
print(m)
e=np.eye(5) #Identity matrix
print(e)

[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<font color='green'>Flatten:</font> It creates 1-D array from any n-d array  
<font color='green'>Ravel:</font>m It creates 1-D array from any n-d array.

In [43]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.ravel()
print(b)
c=a.flatten()
print(c)
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
e=d.ravel()
print(e)
f=d.flatten()
print(f)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [44]:
import numpy as np
d=np.random.rand(3,4)
print(d)
a=np.random.randint(-4,10,size=(2,3))
print(a)

[[0.30904043 0.8512978  0.72805645 0.94834056]
 [0.96386092 0.10136723 0.01224308 0.96065587]
 [0.70873284 0.4589442  0.23990852 0.73186674]]
[[ 6  9 -3]
 [ 1  6  3]]


In [45]:
import numpy as np
x=np.arange(10,30)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [64]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
#print(np.sec(a))
#print(np.cosec(a))
#print(np.cot(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [63]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,3,4],[6,5,9],[3,8,4]])
print(a)
print(b)
print("Transposed array:")
print(a.transpose())

print("Trace of an array:")
print(np.trace(a))

print("Sum of an array:")
print(a+b)

print("Multiplication of an array:")
print(a.dot(b))
#or
print(a@b)
#or
print(np.matmul(a,b))

print("Determinant:")
print(np.linalg.det(a))
print(np.linalg.det(b))

print("Inverse of an array:")
print(np.linalg.inv(a))
print(np.linalg.inv(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3 4]
 [6 5 9]
 [3 8 4]]
Transposed array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Trace of an array:
15
Sum of an array:
[[ 2  5  7]
 [10 10 15]
 [10 16 13]]
Multiplication of an array:
[[ 22  37  34]
 [ 52  85  85]
 [ 82 133 136]]
[[ 22  37  34]
 [ 52  85  85]
 [ 82 133 136]]
[[ 22  37  34]
 [ 52  85  85]
 [ 82 133 136]]
Determinant:
-9.51619735392994e-16
88.99999999999999
Inverse of an array:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[-0.58426966  0.2247191   0.07865169]
 [ 0.03370787 -0.08988764  0.16853933]
 [ 0.37078652  0.01123596 -0.14606742]]
